project:
  type: book
  output-dir: _site
  resources:
    - images/

execute:
  freeze: auto

book:
  title: "Programming Concepts Course"
  author: "---"
  date: "03.12.2025"
  chapters:
    - index.qmd
    - part: "Вступ та підготовка до курсу"
      chapters: 
        - modules/about-the-course.qmd
    - part: "Тестовий розідл"
      chapters: 
      - modules/lists.qmd
      - modules/dictionaries-tuples-sets.qmd
  sidebar:
    collapse-level: 1

website: 
  title: "Programming Concepts"
  page-footer: 
    center: "© 2025 Vadym Katsel. All rights reserved."
  site-url: "https://vadymkatsel.github.io/programming-concepts"
  repo-url: "https://github.com/vadymkatsel/programming-concepts"
  favicon: images/favicon.png

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: cosmo
    number-sections: false
    css: style.css


