project:
  type: book

book:
  title: "programming-concepts-course"
  author: "---"
  date: "03.12.2025"
  chapters:
    - index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



