project:
  type: book

book:
  title: "programming-concepts-course"
  author: "---"
  date: "03.12.2025"
  chapters:
    - index.qmd
    - modules/lists.qmd
    - modules/dictionaries-tuples-sets.qmd

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: cosmo
    number-sections: false
    css: style.css


