project:
  type: book
  output-dir: _site
  resources:
    - images/

execute:
  freeze: auto

book:
  title: "Programming Concepts Course"
  author:
    - name: Vadym Katsel [Creator & Lead Developer]
    - name: Yevhenii Kozolup [Content Consultant]
  date: "03.12.2025"
  chapters:
    - index.qmd
    - part: "Вступ та підготовка до курсу"
      chapters: 
        - modules/about-the-course.qmd
    - part: "Змінні, типи даних. Математичні операції в Python"
      chapters: 
      - modules/ps-2.qmd
  sidebar:
    collapse-level: 1

website: 
  title: "Programming Concepts"
  page-footer: 
    center: "© 2025 Vadym Katsel. All rights reserved."
  site-url: "https://vadymkatsel.github.io/programming-concepts"
  repo-url: "https://github.com/vadymkatsel/programming-concepts"

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: cosmo
    number-sections: false
    css: style.css
    include-in-header: 
      text: |
        <link rel="icon" type="image/svg+xml" href="https://vadymkatsel.github.io/programming-concepts/images/favicon.svg">
    favicon: images/favicon.svg


